"""empty message

Revision ID: 00a41e817f0d
Revises: None
Create Date: 2019-09-10 15:57:54.226328

"""

# revision identifiers, used by Alembic.
revision = '00a41e817f0d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	op.add_column('hostel_expense', sa.Column('expense_common_per_head', sa.Integer, nullable=True, default=0))
    
    
    
    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('bill_pending')
    op.drop_table('attendance')
    op.drop_table('users')
    op.drop_table('hostel_roles')
    op.drop_table('hostel_expense')
    op.drop_table('roles')
    op.drop_table('hostels')
    # ### end Alembic commands ###
