"""empty message

Revision ID: 29b3efe0350e
Revises: 00a41e817f0d
Create Date: 2019-09-10 16:25:23.131202

"""

# revision identifiers, used by Alembic.
revision = '29b3efe0350e'
down_revision = '00a41e817f0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_expense', sa.Column('expense_common_per_head', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel_expense', 'expense_common_per_head')
    # ### end Alembic commands ###
