"""empty message

Revision ID: 48a9637d6fbd
Revises: 86532ee0f47a
Create Date: 2019-09-16 16:02:50.025083

"""

# revision identifiers, used by Alembic.
revision = '48a9637d6fbd'
down_revision = '86532ee0f47a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_expense', sa.Column('expense_total_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel_expense', 'expense_total_points')
    # ### end Alembic commands ###
