"""empty message

Revision ID: 86532ee0f47a
Revises: c44342a0ce25
Create Date: 2019-09-12 07:53:45.193196

"""

# revision identifiers, used by Alembic.
revision = '86532ee0f47a'
down_revision = 'c44342a0ce25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_expense', sa.Column('expense_common_per_head', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel_expense', 'expense_common_per_head')
    # ### end Alembic commands ###
