"""empty message

Revision ID: a98eda385db2
Revises: 29b3efe0350e
Create Date: 2019-09-12 07:47:33.849956

"""

# revision identifiers, used by Alembic.
revision = 'a98eda385db2'
down_revision = '29b3efe0350e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_expense', sa.Column('expense_common_per_head', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
