"""empty message

Revision ID: c44342a0ce25
Revises: a98eda385db2
Create Date: 2019-09-12 07:51:14.032550

"""

# revision identifiers, used by Alembic.
revision = 'c44342a0ce25'
down_revision = 'a98eda385db2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel_expense', sa.Column('expense_common_per_head', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
